# Generated by Django 2.2.7 on 2019-11-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='tab_type',
            field=models.CharField(default='', max_length=9),
        ),
    ]
