# Generated by Django 2.2.7 on 2019-11-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_tab_tab_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='tab_type',
            field=models.CharField(choices=[('dashboard', 'dashboard'), ('all', 'all')], default='all', max_length=9),
        ),
    ]
