# Generated by Django 2.2.7 on 2019-11-27 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_auto_20191127_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='cancel_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelpt_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='confirm_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirm_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='defective_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defective_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
