# Generated by Django 3.0 on 2019-12-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0005_auto_20191214_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_item',
            name='borrow_tel',
            field=models.CharField(default='', max_length=10),
        ),
    ]
