# Generated by Django 2.2.6 on 2019-10-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_amount',
        ),
    ]
