# Generated by Django 2.2.6 on 2019-10-31 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20191031_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
