# Generated by Django 2.2.6 on 2019-10-31 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20191031_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 15, 46, 38, 168735), editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 15, 46, 38, 168735)),
        ),
    ]
