# Generated by Django 2.2.6 on 2019-11-01 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20191031_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 1, 23, 17, 24, 298586), editable=False),
        ),
    ]
