# Generated by Django 2.2.6 on 2019-11-01 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_auto_20191102_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 0, 43, 27, 42686), editable=False),
        ),
    ]
