# Generated by Django 2.2.6 on 2019-11-02 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_auto_20191102_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 15, 59, 50, 87232), editable=False),
        ),
    ]
