# Generated by Django 2.2.6 on 2019-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_auto_20191102_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
