# Generated by Django 2.2.7 on 2019-11-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0026_item_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reserve_status',
            field=models.CharField(default='01', max_length=2),
        ),
    ]
