# Generated by Django 2.2.7 on 2019-11-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0027_item_reserve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount_forreserve',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
