# Generated by Django 2.2.7 on 2019-11-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0029_auto_20191120_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='amount_forreserve',
            new_name='lackamount_reserve',
        ),
    ]
