# Generated by Django 2.2.7 on 2019-11-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0030_auto_20191124_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='lackamount_reserve',
            new_name='amount_forreserve',
        ),
    ]
